# Generated by Django 4.2.3 on 2023-07-15 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address_alter_user_date_of_birth_drivers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='drivers',
            new_name='Driver',
        ),
    ]
