# Generated by Django 4.2.3 on 2023-07-16 12:52

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_rename_profile_user_profile_pic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="date_of_birth",
            field=models.DateField(
                null=True, validators=[utils.validators.validate_date_of_birth]
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="driver_identity_document",
            field=models.CharField(
                choices=[("PS", "Passport"), ("Cart", "Carte D'electeur")],
                default="Cart",
                max_length=40,
                verbose_name="Identity document type",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="driving_school_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="driving_school_certificate",
                verbose_name="Driving School Certificate",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="medical_test",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="medical_test",
                verbose_name="Medical Test",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="registration_form",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="formulaire",
                verbose_name="Formulaire d'enregistrement",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pic"),
        ),
    ]
