# Generated by Django 4.2.3 on 2023-07-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_driver_date_of_birth_driver_driver_identity_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='divers_photo', verbose_name='Driver Photo'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Driver Names'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Driver Last Names'),
        ),
    ]
