# Generated by Django 4.2.3 on 2023-07-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_driver_profile_pic_alter_driver_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
