# Generated by Django 4.2.3 on 2023-07-20 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_driver_address_delete_address_delete_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
