# Generated by Django 4.2.3 on 2023-07-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=10, null=True, verbose_name='sex'),
        ),
    ]
