# Generated by Django 4.2.4 on 2023-08-11 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_site_adress_site_manager_site_name_site_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='manager',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
