# Generated by Django 4.2.4 on 2023-08-11 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_site_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='manager',
        ),
        migrations.AddField(
            model_name='site',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
