# Generated by Django 4.2.4 on 2023-08-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_site_manager_site_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='Site location city'),
        ),
        migrations.AddField(
            model_name='site',
            name='province',
            field=models.CharField(max_length=255, null=True, verbose_name='Site location province'),
        ),
    ]
