# Generated by Django 4.2.4 on 2023-08-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_site_city_site_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='adress',
            field=models.CharField(max_length=500, null=True, verbose_name='Site adress'),
        ),
        migrations.AlterField(
            model_name='site',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='site',
            name='province',
            field=models.CharField(max_length=255, null=True, verbose_name='Province'),
        ),
    ]
