# Generated by Django 4.2.4 on 2023-08-13 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_site_manager_user_is_sitemanager_user_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site', to='accounts.site'),
        ),
    ]
