# Generated by Django 4.2.4 on 2023-08-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
