# Generated by Django 4.2.3 on 2023-07-10 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_category_name_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='answer_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.option'),
        ),
    ]
