# Generated by Django 4.2.3 on 2023-07-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizscore_answer_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizscore',
            name='quiz_score',
        ),
    ]
