# Generated by Django 4.2.3 on 2023-07-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quizscore_quiz_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizscore',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quizscore',
            name='quiz',
            field=models.ManyToManyField(blank=True, null=True, to='quiz.quiz'),
        ),
    ]
