# Generated by Django 4.2.3 on 2023-07-10 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_quizscore_quiz_quizscore_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizscore',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quizscore',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quiz'),
        ),
    ]
