# Generated by Django 4.2.3 on 2023-07-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_question_answers_user_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_answers', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='user_answers',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Questions', to='quiz.question'),
        ),
    ]
