# Generated by Django 4.2.3 on 2023-07-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_question_answers_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_answers',
            old_name='choice',
            new_name='title',
        ),
    ]
