# Generated by Django 4.2.3 on 2023-07-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_rename_question_answers_questionanswers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswers',
            name='title',
        ),
        migrations.AddField(
            model_name='questionanswers',
            name='answer_text',
            field=models.CharField(max_length=200, null=True, verbose_name='Answer'),
        ),
    ]
