# Generated by Django 4.2.3 on 2023-07-17 15:17

from django.db import migrations, models
import django.db.models.deletion
import quiz.validators


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_rename_questionanswers_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=1024, verbose_name='Numero et Rue')),
                ('address2', models.CharField(max_length=1024, verbose_name='Quartier et commune')),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True, verbose_name='ZIP / Postal code')),
                ('city', models.CharField(max_length=1024, verbose_name='City')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=10, unique=True, verbose_name='Driving licence Form number')),
                ('licence_type', models.CharField(choices=[('Nat', 'National'), ('Inter', 'International')], default='Nat', max_length=10, verbose_name='Driving license type')),
                ('first_name', models.CharField(max_length=255, verbose_name='Driver Names')),
                ('last_name', models.CharField(max_length=255, verbose_name='Driver Last Names')),
                ('driver_nationality', models.CharField(max_length=255, verbose_name='Driver Nationality')),
                ('driver_identity_document', models.CharField(choices=[('PS', 'Passport'), ('Cart', "Carte D'electeur")], default='Cart', max_length=40, verbose_name='Identity document type')),
                ('driver_identity_document_number', models.CharField(max_length=255, verbose_name='Driver Identity document number')),
                ('date_of_birth', models.DateField(null=True, validators=[quiz.validators.validate_date_of_birth])),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='divers_photo', verbose_name='Driver Photo')),
                ('registration_form', models.FileField(blank=True, null=True, upload_to='formulaire', verbose_name="Formulaire d'enregistrement")),
                ('driving_school_certificate', models.FileField(blank=True, null=True, upload_to='driving_school_certificate', verbose_name='Driving School Certificate')),
                ('medical_test', models.FileField(blank=True, null=True, upload_to='medical_test', verbose_name='Medical Test')),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_address', to='quiz.address')),
            ],
        ),
    ]
