# Generated by Django 4.2.3 on 2023-07-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_remove_user_answers_user_user_answers_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='Questions_Illustration', verbose_name='Question Picture'),
        ),
    ]
