# Generated by Django 4.2.3 on 2023-07-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_rename_pic_question_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='sex',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=10, null=True, verbose_name='sex'),
        ),
    ]
