# Generated by Django 4.2.3 on 2023-08-04 17:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_driver_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('medical_test', models.FileField(blank=True, null=True, upload_to='medical_test', verbose_name='Medical Test')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='driver',
            name='address',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='medical_test',
        ),
        migrations.AddField(
            model_name='driver',
            name='adress_area',
            field=models.CharField(max_length=255, null=True, verbose_name='Area Name'),
        ),
        migrations.AddField(
            model_name='driver',
            name='adress_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adress Number'),
        ),
        migrations.AddField(
            model_name='driver',
            name='adress_street',
            field=models.CharField(max_length=255, null=True, verbose_name='Adress street'),
        ),
        migrations.AddField(
            model_name='driver',
            name='adress_township',
            field=models.CharField(max_length=255, null=True, verbose_name='Adress Township'),
        ),
        migrations.AddField(
            model_name='driver',
            name='city',
            field=models.CharField(max_length=1024, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='driver',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='driver',
            name='middle_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Driver Middle Name'),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='driver',
            name='place_birth',
            field=models.CharField(max_length=255, null=True, verbose_name='Driver place birth'),
        ),
        migrations.AddField(
            model_name='driver',
            name='state',
            field=models.CharField(max_length=1024, null=True, verbose_name='Province'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='medicalinfo',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Driver_medical', to='quiz.driver'),
        ),
    ]
