# Generated by Django 4.2.3 on 2023-08-05 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_rename_user_answers_driveranswers'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('test_type', models.CharField(choices=[('Th', 'Théorie'), ('Pr', 'Practical')], default='Th', max_length=15, verbose_name='Driving license type')),
                ('score', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Obtained score')),
                ('answer_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.answers')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.driver')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Questions', to='quiz.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DriverAnswers',
        ),
    ]
