# Generated by Django 4.2.3 on 2023-08-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_alter_quizanswers_score_alter_quizanswers_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswers',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Obtained score'),
        ),
    ]
