# Generated by Django 4.2.3 on 2023-08-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0027_alter_quizanswers_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswers',
            name='passed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Quiz Scheduled on'),
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='schedule_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Quiz Scheduled on'),
        ),
    ]
