# Generated by Django 4.2.3 on 2023-08-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_quizanswers_passed_on_quizanswers_schedule_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizanswers',
            old_name='answer_option',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='quizanswers',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='quizanswers',
            name='passed_on',
        ),
        migrations.RemoveField(
            model_name='quizanswers',
            name='schedule_on',
        ),
        migrations.RemoveField(
            model_name='quizanswers',
            name='score',
        ),
        migrations.RemoveField(
            model_name='quizanswers',
            name='test_type',
        ),
        migrations.AlterField(
            model_name='quizanswers',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.question'),
        ),
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('test_type', models.CharField(choices=[('Th', 'Theory'), ('Pr', 'Practical')], default='Th', max_length=15, verbose_name='Quiz type')),
                ('schedule_on', models.DateTimeField(blank=True, null=True, verbose_name='Quiz Scheduled on')),
                ('passed_on', models.DateTimeField(blank=True, null=True, verbose_name='Quiz Scheduled on')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Obtained score')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.driver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quizanswers',
            name='quizscore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.quizscore'),
        ),
    ]
