# Generated by Django 4.2.3 on 2023-08-05 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0031_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswers',
            name='quizscore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_score_answers', to='quiz.quizscore'),
        ),
    ]
