# Generated by Django 4.2.3 on 2023-08-06 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_alter_quizanswers_quizscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
