# Generated by Django 4.2.3 on 2023-08-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0033_remove_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='passed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Quiz passed on'),
        ),
    ]
