# Generated by Django 4.2.3 on 2023-08-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0034_alter_quizscore_passed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Question'),
        ),
    ]
