# Generated by Django 4.2.4 on 2023-08-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0035_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Question'),
        ),
    ]
