# Generated by Django 4.2.4 on 2023-08-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0038_alter_driver_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.AddField(
            model_name='driver',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
