# Generated by Django 4.2.4 on 2023-08-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0042_quizscore_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizscore',
            name='passed_on',
        ),
        migrations.AddField(
            model_name='quizscore',
            name='taken',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='taken'),
        ),
    ]
