# Generated by Django 4.2.4 on 2023-08-13 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_site'),
        ('quiz', '0043_remove_quizscore_passed_on_quizscore_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_site', to='accounts.site'),
        ),
    ]
