# Generated by Django 4.2.4 on 2023-08-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_site'),
        ('quiz', '0044_alter_quizscore_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_site', to='accounts.site'),
        ),
    ]
